FROM maven:3.5.2-jdk-8 AS build

WORKDIR /usr/tracedemo

COPY oneagent ./oneagent
COPY src ./demo/src
COPY pom.xml ./demo/pom.xml 
COPY provider.sh ./provider.sh

RUN mvn -f /usr/tracedemo/demo/pom.xml clean package

FROM openjdk:8-jre-alpine

COPY --from=build /usr/tracedemo /usr/tracedemo

ENTRYPOINT sh /usr/tracedemo/provider.sh